apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-gke
  template:
    metadata:
      labels:
        app: hello-gke
    spec:
      containers:
      - name: hello-gke
        image: gcr.io/algebraic-inn-256717/hello-gke:latest
        ports:
        - containerPort: 8080