# Manual trigger for GitHub Actions
# Manual trigger for GitHub Actions
on:
  workflow_dispatch:
  push:
    branches:
      - feature/internal-lb
name: Build and Publish to GAR

# Trigger reload for GitHub Actions workflow UI
name: Build and Publish to GAR


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  REPOSITORY: ${{ vars.REPOSITORY }}
  REGION: us-central1
  IMAGE: ${{ vars.IMAGE }}

jobs:
  build-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Docker for Artifact Registry
        run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Build HelloWorld_1.2 Docker image
        run: |
          IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:HelloWorld_1.2
          docker build -t "$IMAGE_URI" --build-arg VERSION=1.2 hello-gke
      - name: Push HelloWorld_1.2 Docker image
        run: |
          IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:HelloWorld_1.2
          docker push "$IMAGE_URI"
