name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/YOUR_PROJECT_NUMBER/locations/global/workloadIdentityPools/YOUR_POOL_ID/providers/YOUR_PROVIDER_ID'
        service_account: 'YOUR_SERVICE_ACCOUNT_EMAIL'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image to GAR
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/hello-repo/hello-gke:${{ github.sha }}

    - name: Set up kubectl
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: YOUR_PROJECT_ID
        install_components: kubectl

    - name: Configure GKE credentials
      run: |
        gcloud container clusters get-credentials YOUR_CLUSTER_NAME \
          --zone YOUR_CLUSTER_ZONE \
          --project YOUR_PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/gke-test \
          hello-gke=us-central1-docker.pkg.dev/YOUR_PROJECT_ID/hello-repo/hello-gke:${{ github.sha }}
        kubectl rollout status deployment/gke-test
