<<<<<<< HEAD
=======


>>>>>>> a7f8ae2 (add manual trigger)
name: Build and Deploy to GKE

on:
  push:
    branches:
      - feature/documentation-add
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: hello-autopilot
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: gke-test
  REPOSITORY: hello-gke-repo
  REGION: us-central1
  IMAGE: hello-gke
  IMAGE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate to Google Cloud using service account
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}


    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        project_id: ${{ secrets.GKE_PROJECT }}

    # Install gke-gcloud-auth-plugin for kubectl authentication
    - name: Install gke-gcloud-auth-plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

  # Configure Docker to use gcloud as a credential helper for Artifact Registry (commented out, not needed for Helm-only deploys)
  # - name: Configure Docker
  #   run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

    # Get GKE credentials
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

  # Build Docker image (commented out to skip build step)
  # - name: Build Docker image
  #   run: |
  #     IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
  #     docker build \
  #       --file hello-gke/Dockerfile \
  #       --tag "$IMAGE_URI" \
  #       --build-arg GITHUB_SHA="$GITHUB_SHA" \
  #       --build-arg GITHUB_REF="$GITHUB_REF" \
  #       hello-gke

  # Push Docker image to GCR (commented out to skip push step)
  # - name: Publish Docker image
  #   run: |
  #     IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
  #     docker push "$IMAGE_URI"

    # Install Helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    # Deploy to GKE using Helm
    - name: Deploy to GKE with Helm
      run: |
        helm upgrade --install hello-gke ./helm-chart \
          --set image.repository=${IMAGE_REPOSITORY} \
          --set image.tag=${IMAGE_TAG}
        kubectl rollout status deployment/hello-gke
        kubectl get services -o wide
        



