name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID'
        service_account: 'github-deployer@YOUR_PROJECT_ID.iam.gserviceaccount.com'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker LOCATION-docker.pkg.dev

    - name: Build and push Docker image
      run: |
        docker build -t LOCATION-docker.pkg.dev/YOUR_PROJECT_ID/REPO_NAME/IMAGE_NAME:$GITHUB_SHA .
        docker push LOCATION-docker.pkg.dev/YOUR_PROJECT_ID/REPO_NAME/IMAGE_NAME:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy SERVICE_NAME \
          --image LOCATION-docker.pkg.dev/YOUR_PROJECT_ID/REPO_NAME/IMAGE_NAME:$GITHUB_SHA \
          --region REGION \
          --platform managed \
          --allow-unauthenticated

env:
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}

steps:
  - name: Decode service account key
    run: echo "$GKE_SA_KEY" | base64 --decode > "${HOME}/gcloud.json"

  - name: Authenticate to Google Cloud
    run: gcloud auth activate-service-account --key-file="${HOME}/gcloud.json"

