name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: hello-autopilot
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: gke-test
  REPOSITORY: hello-gke-repo
  REGION: us-central1
  IMAGE: hello-gke

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate to Google Cloud using service account
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GKE_SA_KEY }}

    # Setup gcloud CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use gcloud as a credential helper for Artifact Registry
    - name: Configure Docker
      run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

    # Get GKE credentials
    - name: Get GKE credentials
      run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

    # Build Docker image
    - name: Build Docker image
      run: |
        IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
        docker build \
          --file hello-gke/Dockerfile \
          --tag "$IMAGE_URI" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          hello-gke

    # Push Docker image to GCR
    - name: Publish Docker image
      run: |
        IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
        docker push "$IMAGE_URI"

    # Set up Kustomize
    - name: Set up Kustomize
      run: |
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy to GKE
    - name: Deploy to GKE
      run: |
        IMAGE_URI=us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
        ./kustomize edit set image us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest=$IMAGE_URI
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
        

