
name: Build and Deploy to GKE
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_ZONE: us-central1
  DEPLOYMENT_NAME: ${{ vars.DEPLOYMENT_NAME }}
  REPOSITORY: ${{ vars.REPOSITORY }}
  REGION: us-central1
  IMAGE: ${{ vars.IMAGE }}
  IMAGE_REPOSITORY: ${{ vars.IMAGE_REPOSITORY }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Echo deployment variables
        run: |
          echo "GKE_CLUSTER: $GKE_CLUSTER"
          echo "DEPLOYMENT_NAME: $DEPLOYMENT_NAME"
          echo "REPOSITORY: $REPOSITORY"
          echo "IMAGE: $IMAGE"
          echo "IMAGE_REPOSITORY: $IMAGE_REPOSITORY"
          echo "IMAGE_TAG: $IMAGE_TAG"

      - name: Deploy to GKE with Helm
        run: |
          helm upgrade --install hello-gke ./helm-chart \
            --set image.repository=${IMAGE_REPOSITORY} \
            --set image.tag=${IMAGE_TAG}
          kubectl rollout status deployment/hello-gke
          kubectl get services -o wide
        



